---
# (Optional) when using custom network
# networks:
#   yournetwork:
#     external: true
volumes:
  mariadb-data:
services:
  mariadb:
    container_name: mariadb:11.1.2
    image: mariadb:latest
    # (Optional) remove this section when you don't want to expose
    ports:
      - 3306:3306
    environment:
      # (Optional) remove this section, when using random, or empty root password
      - MARIADB_ROOT_PASSWORD=your-root-password
      # (Optional) when using random, or empty root password
      # - MARIADB_RANDOM_ROOT_PASSWORD=true
      # - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=databaseName
      - MARIADB_USER=UserName
      - MARIADB_PASSWORD=Password
    volumes:
      - mariadb-data:/var/lib/mysql
    # (Optional) when using custom network
    # networks:
    #   - yournetwork
    restart: unless-stopped
